luoghi=['Qualsiasi',
 'Como',
 'Fabriano',
 'Genova',
 'Göttweig',
 'Lucca / Pisa',
 'Milano',
 'Piacenza',
 'Roma',
 'Salò',
 'Udine',
 'Venezia',
 'Verona',
 'Vicenza',
 'area toscana',
 'var. Verona']
classi=[('Qualsiasi', 'Qualsiasi'),
 ('1.', 'Elementi del paesaggio'),
 ('1.1.', '↪Montagne'),
 ('2.', 'Figurazioni astrali'),
 ('2.1.', '↪Luna'),
 ('2.1.3.', '↪↪Tre mezze lune'),
 ('2.2.', '↪Stella'),
 ('3.', 'Figurazioni animali'),
 ('3.1.', '↪Esseri mitologici / chimerici'),
 ('3.2.', '↪Mammiferi'),
 ('3.2.1.', '↪↪Cane'),
 ('3.2.2.', '↪↪Bue / Toro'),
 ('3.2.2.1.', '↪↪↪Testa di bue'),
 ('3.2.3.', '↪↪Cervo'),
 ('3.2.3.1.', '↪↪↪Testa / busto di cervo'),
 ('3.3.', '↪Volatili'),
 ('3.3.1.', '↪↪Anatra'),
 ('3.3.2.', '↪↪Cigno'),
 ('3.3.3.', '↪↪Uccello n. d.'),
 ('4.', 'Figurazioni umane'),
 ('4.1.', '↪Angeli / Santi'),
 ('5.', 'Figurazioni vegetali'),
 ('5.1.', '↪Fiori'),
 ('6.', 'Geometrie miste'),
 ('6.1.', '↪Cerchio'),
 ('7.', 'Lettere'),
 ('7.1.', '↪P'),
 ('8.', 'Oggetti'),
 ('8.1.', '↪Ancora'),
 ('8.2.', '↪Arco / Freccia'),
 ('8.3.', '↪Bilancia'),
 ('8.4.', '↪Cappello'),
 ('9.', 'Simboli')]
